version: '2'
services:

    mysql:
        image: mysql:8
        volumes:
            - ${HUMBLE_DATA}/mysql:/var/lib/mysql
            - ./services/mysql/my.cnf:/etc/mysql/my.cnf
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: bikesharing

    pma:
        image: phpmyadmin/phpmyadmin:4.6.4-1
        links:
            - mysql:db
        environment:
            - PMA_USER=${MYSQL_USER}
            - PMA_PASSWORD=${MYSQL_PASSWORD}
            - PHP_UPLOAD_MAX_FILESIZE=999999999
        depends_on:
            - mysql
        ports:
            - ${HUMBLE_PORT}:80

    free-bikes:
        image: node:7.4
        volumes:
            - ./services/free-bikes/node-app:/usr/src/app
        working_dir: /usr/src/app
        entrypoint: ["npm", "run", "start:dev"]
        environment:
            LOG_LEVEL: info
            SCRAPE_INTERVAL: ${SCRAPE_INTERVAL_SHORT}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        links:
            - mysql:mysql

    hubs:
        image: node:7.4
        volumes:
            - ./services/hubs/node-app:/usr/src/app
        working_dir: /usr/src/app
        entrypoint: ["npm", "run", "start:dev"]
        environment:
            LOG_LEVEL: info
            SCRAPE_INTERVAL: ${SCRAPE_INTERVAL_SHORT}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        links:
            - mysql:mysql

    hubs-info:
        image: node:7.4
        volumes:
            - ./services/hubs-info/node-app:/usr/src/app
        working_dir: /usr/src/app
        entrypoint: ["npm", "run", "start:dev"]
        environment:
            LOG_LEVEL: info
            SCRAPE_INTERVAL: ${SCRAPE_INTERVAL_LONG}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        links:
            - mysql:mysql
