version: '2'
services:

    mysql:
        image: mysql:8
        volumes:
            - ${HUMBLE_DATA}/mysql:/var/lib/mysql
            - ./services/mysql/my.cnf:/etc/mysql/my.cnf
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: bikesharing
        mem_limit: ${MEM_LIMIT_MYSQL}

    pma:
        image: phpmyadmin/phpmyadmin:4.6.4-1
        links:
            - mysql:db
        environment:
            - PMA_USER=${MYSQL_USER}
        depends_on:
            - mysql
        ports:
            - ${HUMBLE_PORT}:80
        mem_limit: ${MEM_LIMIT_PMA}

    monitor:
        image: node:7.4
        volumes:
            - ./services/monitor/node-app:/usr/src/app
        working_dir: /usr/src/app
        entrypoint: ["npm", "run", "start:dev"]
        environment:
            LOG_LEVEL: info
            SCRAPE_NETWORK_ID: ${SCRAPE_NETWORK_ID}
            SCRAPE_INTERVAL_SHORT: ${SCRAPE_INTERVAL_SHORT}
            SCRAPE_INTERVAL_LONG: ${SCRAPE_INTERVAL_LONG}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_INSERT_BACTH: ${MYSQL_INSERT_BACTH}
            MYSQL_INSERT_DELAY: ${MYSQL_INSERT_DELAY}
        links:
            - mysql:mysql
        mem_limit: ${MEM_LIMIT_MONITOR}
